export const CHANGE_CATEGORY="CHANGE_CATEGORY"
export const GET_CATEGORİES_SUCCESS="GET_CATEGORİES_SUCCESS" 

export const GET_NEWS_SUCCESS="GET_NEWS_SUCCESS"
export const GET_NEWSPAGE_SUCCESS="GET_NEWSPAGE_SUCCESS"
